# Generated by Django 2.0.3 on 2018-03-23 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_feature_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='last_updates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
