# Generated by Django 2.0.3 on 2018-03-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180323_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to='news')),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('last_updates', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
